### ISSUE TITLE
Call init/fini handlers

### ISSUE THREAD

**Issue by xyzz** [xyzz/vita-newlib#1]
Probably just need to call `__libc_init_array`, `__libc_fini_array` from crt0 but it's better to test it.

**Comment by frangarcj** [comment]
https://gist.github.com/frangarcj/f5bbabd3f25887ad2091

**Comment by xyzz** [comment]
#5

**Comment by xyzz** [comment]
d4564552689ba57ae16d7b6c20161fbe3acd1d21
