### ISSUE TITLE
Implement remaining syscalls

### ISSUE THREAD

**Issue by xyzz** [xyzz/vita-newlib#3]
- [x] _exit
- [x] _fstat_r
- [x] _gettimeofday_r
- [x] _stat_r
- [x] _unlink_r
- [x] _times_r
- [x] _rename_r

**Comment by endrift** [comment]
_gettimeofday_r: https://github.com/xyzz/vita-newlib/pull/7

**Comment by xyzz** [comment]
All done, yay!
