### ISSUE TITLE
Implementation for _stat_r requires linking SceRtc_stub

### ISSUE THREAD

**Issue by cy33hc** [xyzz/vita-newlib#9]
New implementation for _stat_r added dependency on sceRtcGetTime_t which is in libSceRtc_stub.

![stat_r](https://cloud.githubusercontent.com/assets/4947747/10038563/a193c554-617c-11e5-8390-975add19da12.png)

Need to add back -lSceRtc_stub into vita.patch

![vitasdk_build](https://cloud.githubusercontent.com/assets/4947747/10038567/ae0823b6-617c-11e5-812a-332929617a96.png)

**Comment by xyzz** [comment]
https://github.com/xyzz/vitasdk-buildscripts/commit/1b3d181c87cc1beee4443ea904f37ad63b2bbcfa
